name = "BeaData"
uuid = "acefaad2-17a4-5d8b-aa08-e18ef75dd0cf"
authors = ["Stephen Nicar <stephenbnicar@gmail.com>"]
version = "0.5"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Retry = "20febd7b-183b-5ae2-ac4a-720e7ce64774"

[compat]
DataFrames = "^0.20.2, 0.21, 0.22"
DataStructures = "^0.18"
HTTP = "^0.8.14, 0.9"
JSON = "^0.21"
Retry = "^0.4"
julia = "^1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
